language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"

env:
    global:
        - WHEEL="pip install --find-links http://wheels.astropy.org/ --find-links http://wheels2.astropy.org/ --use-wheel --use-mirrors"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-numpy python-scipy
  - sudo apt-get install -qq python3-numpy python3-scipy
  - rm /home/travis/virtualenv/python2.7/lib/python2.7/no-global-site-packages.txt
  - rm /home/travis/virtualenv/python3.2/lib/python3.2/no-global-site-packages.txt
  - rm /home/travis/virtualenv/python3.3/lib/python3.3/no-global-site-packages.txt

  - pip install setuptools --upgrade --use-mirrors
  - pip install pip --upgrade --use-mirrors
  - pip install wheel --use-mirrors
  - $WHEEL numpy==1.7.1 scipy==0.12.1
  - pip install https://github.com/dimazest/sparsesvd/archive/72adffd01820aff446a826.zip#egg=sparsesvd-cffi-0.2.2-dev

install:
  - $WHEEL .
# command to run tests
script: python setup.py test
