language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"

env:
    global:
        - WHEEL="pip install --find-links https://dl.dropboxusercontent.com/u/50040986/index/index.html --use-wheel --use-mirrors"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-numpy python-scipy
  - pip install setuptools --upgrade --use-mirrors
  - pip install pip --upgrade --use-mirrors
  - pip install wheel --use-mirrors
  - $WHEEL numpy==1.7.1 scipy==0.12.1
  - easy_install https://dl.dropboxusercontent.com/u/50040986/index/sparsesvd-cffi-0.2.3-dev.tar.gz
  - python -c 'import sysconfig; print(sysconfig.get_config_var("SO"))'
  - 'ls /home/travis/virtualenv/python3.3/lib/python3.3/site-packages/sparsesvd_cffi-0.2.3_dev-py3.3-linux-x86_64.egg/ && true '
install:
  - $WHEEL .
# command to run tests
script: python setup.py test
