language: python
python:
  - "2.7"
  - "3.3"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-numpy python-scipy python-matplotlib
  - sudo apt-get install -qq python33-numpy python3.3-scipy python33-matplotlib
  - rm /home/travis/virtualenv/python2.7/lib/python2.7/no-global-site-packages.txt
  - rm /home/travis/virtualenv/python3.3/lib/python3.3/no-global-site-packages.txt
# command to install dependencies
install:
  - pip install cython --use-mirrors
  - pip install . --use-mirrors
# command to run tests
script: python setup.py test
